// Generates src/styles/theme.css: Material 3 colour roles for light and dark, from one seed colour.
// The Android app uses the wallpaper's dynamic colour; the web has none, so we use the launcher icon colour.
// Run with `pnpm theme` after changing SEED.
import { writeFileSync } from 'node:fs';
import {
  argbFromHex,
  DynamicColor,
  hexFromArgb,
  Hct,
  MaterialDynamicColors,
  SchemeTonalSpot,
} from '@material/material-color-utilities';

const SEED = '#D84F2A';
const OUTPUT = new URL('../src/styles/theme.css', import.meta.url);

const kebab = (name) => name.replace(/_/g, '-').replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();

function tokens(isDark) {
  const scheme = new SchemeTonalSpot(Hct.fromInt(argbFromHex(SEED)), isDark, 0);
  return Object.values(MaterialDynamicColors)
    .filter((color) => color instanceof DynamicColor && !color.name.includes('palette_key_color'))
    .map((color) => `  --md-${kebab(color.name)}: ${hexFromArgb(color.getArgb(scheme))};`)
    .join('\n');
}

const css = `/* Generated by scripts/generate-theme.js from seed ${SEED}. Do not edit by hand. */
:root {
  color-scheme: light;
${tokens(false)}
}

@media (prefers-color-scheme: dark) {
  :root {
    color-scheme: dark;
${tokens(true).replace(/^ {2}/gm, '    ')}
  }
}
`;

writeFileSync(OUTPUT, css);
console.log(`Wrote ${OUTPUT.pathname}`);
